import { Project, Skill, BlogPost } from '@/types';

export const projects: Project[] = [
  {
    slug: 'pacitankab-go-id',
    title: 'Portal Resmi Kabupaten Pacitan',
    description: 'Website utama Pemerintah Kabupaten Pacitan sebagai pusat informasi publik, layanan, dan transparansi pemerintahan.',
    longDescription: 'Mengelola portal resmi pacitankab.go.id dengan fokus pada uptime, keamanan, dan performa. Bertanggung jawab pada infrastruktur server, deployment, dan pemeliharaan sistem.',
    featured: true,
    tags: ['Linux', 'Docker', 'Proxmox', 'Nginx'],
    image: '/projects/pacitankab.png',
    liveUrl: 'https://pacitankab.go.id',
  },
  {
    slug: 'data-pacitankab',
    title: 'Data Pacitan',
    description: 'Platform data sektoral Kabupaten Pacitan untuk pengumpulan, validasi, dan publikasi data perangkat daerah.',
    longDescription: 'Membangun dan memelihara sistem data.pacitankab.go.id untuk mendukung Satu Data Indonesia di tingkat kabupaten.',
    featured: true,
    tags: ['Data Analysis', 'Linux', 'Docker', 'PostgreSQL'],
    image: '/projects/data-pacitan.png',
    liveUrl: 'https://data.pacitankab.go.id',
  },
  {
    slug: 'opendata-pacitankab',
    title: 'Open Data Pacitan',
    description: 'Portal Open Data Kabupaten Pacitan untuk keterbukaan data publik yang mudah diakses dan digunakan kembali.',
    longDescription: 'Mengelola opendata.pacitankab.go.id sebagai wujud transparansi dan partisipasi publik berbasis data terbuka.',
    featured: true,
    tags: ['Open Data', 'CKAN', 'Docker', 'Linux'],
    image: '/projects/opendata.png',
    liveUrl: 'https://opendata.pacitankab.go.id',
  },
  {
    slug: 'geoportal-pacitankab',
    title: 'Geoportal Pacitan',
    description: 'Geoportal Kabupaten Pacitan untuk visualisasi dan layanan data geospasial tematik kewilayahan.',
    longDescription: 'Memelihara infrastruktur geoportal.pacitankab.go.id untuk integrasi peta, layanan WMS/WFS, dan analisis spasial.',
    featured: true,
    tags: ['GIS', 'GeoServer', 'Linux', 'Docker'],
    image: '/projects/geoportal.png',
    liveUrl: 'https://geoportal.pacitankab.go.id',
  },
  {
    slug: 'dataviz-pacitankab',
    title: 'Dataviz Pacitan',
    description: 'Dashboard visualisasi data Kabupaten Pacitan untuk eksplorasi data interaktif dan pengambilan keputusan berbasis data.',
    longDescription: 'Mengembangkan dataviz.pacitankab.go.id untuk mengubah data mentah menjadi insight visual yang mudah dipahami pimpinan dan publik.',
    featured: true,
    tags: ['Data Visualization', 'Metabase', 'Linux', 'Docker'],
    image: '/projects/dataviz.png',
    liveUrl: 'https://dataviz.pacitankab.go.id',
  },
  {
    slug: 'masjid-al-falaq-kriyan',
    title: 'Masjid Al-Falaq Kriyan',
    description: 'Website resmi Masjid Al-Falaq Kriyan Sidoharjo Pacitan dengan jadwal shalat, tadabbur harian, kajian, laporan infaq transparan, dan kontak taqmir.',
    longDescription: 'Mengelola website Masjid Al-Falaq Kriyan Sidoharjo Pacitan berbasis Next.js. Fitur meliputi jadwal shalat harian, tadabbur satu ayat, publikasi kajian via WordPress, laporan infaq mengikuti Google Sheet bendahara, integrasi YouTube kajian, serta kontak taqmir dan nomor penting.',
    featured: true,
    tags: ['Next.js', 'Linux', 'Nginx', 'Docker'],
    image: '/projects/masjid-al-falaq.png',
    liveUrl: 'https://masjidalfalaq.pacitankab.web.id/',
  },
  {
    slug: 'infrastruktur-jaringan-pemkab',
    title: 'Infrastruktur & Keamanan Jaringan Pemkab',
    description: 'Perancangan, pembangunan, dan pemeliharaan infrastruktur server, virtualisasi, dan keamanan jaringan di lingkungan Pemkab Pacitan.',
    featured: false,
    tags: ['Proxmox', 'Mikrotik', 'Fortigate', 'Linux'],
    image: '/projects/infra.png',
  },
];

export const skills: Skill[] = [
  { name: 'Linux Server Administration', category: 'Infrastructure', level: 92 },
  { name: 'Proxmox VE', category: 'Infrastructure', level: 88 },
  { name: 'Docker Engine', category: 'DevOps', level: 85 },
  { name: 'Mikrotik', category: 'Network', level: 87 },
  { name: 'Fortigate', category: 'Network', level: 82 },
  { name: 'Nginx', category: 'Infrastructure', level: 80 },
  { name: 'PostgreSQL', category: 'Database', level: 78 },
  { name: 'Data Analysis', category: 'Data', level: 85 },
  { name: 'Network Management', category: 'Network', level: 86 },
  { name: 'Virtualization', category: 'Infrastructure', level: 88 },
];

export const blogs: BlogPost[] = [
  {
    slug: 'manajemen-infrastruktur-pemerintah-daerah',
    title: 'Manajemen Infrastruktur Server untuk Layanan Pemerintah Daerah',
    excerpt: 'Strategi menjaga uptime dan keamanan portal pemerintah dengan Linux, Proxmox, dan Docker di lingkungan Pemkab Pacitan.',
    date: '2025-03-20',
    readingTime: '8 min read',
    tags: ['Infrastructure', 'Linux', 'Proxmox'],
  },
  {
    slug: 'satu-data-indonesia-pacitan',
    title: 'Implementasi Satu Data Indonesia di Kabupaten Pacitan',
    excerpt: 'Alur pengumpulan, validasi, dan publikasi data sektoral untuk mendukung kebijakan berbasis data.',
    date: '2025-03-10',
    readingTime: '7 min read',
    tags: ['Data', 'Satu Data', 'Open Data'],
  },
  {
    slug: 'keamanan-jaringan-mikrotik-fortigate',
    title: 'Keamanan Jaringan Pemerintah dengan Mikrotik & Fortigate',
    excerpt: 'Best practice segmentasi jaringan, firewall policy, dan monitoring untuk infrastruktur kritikal pemerintah.',
    date: '2025-02-28',
    readingTime: '9 min read',
    tags: ['Network', 'Mikrotik', 'Fortigate'],
  },
  {
    slug: 'visualisasi-data-untuk-kebijakan',
    title: 'Visualisasi Data untuk Pengambilan Keputusan Daerah',
    excerpt: 'Bagaimana dashboard dataviz membantu pimpinan memahami tren dan capaian pembangunan secara cepat.',
    date: '2025-02-15',
    readingTime: '6 min read',
    tags: ['Data Visualization', 'Data Analysis'],
  },
  {
    slug: 'geoportal-data-spasial-pacitan',
    title: 'Membangun Geoportal: Integrasi Data Spasial Pacitan',
    excerpt: 'Pengelolaan data geospasial tematik dan layanan peta untuk perencanaan wilayah yang akurat.',
    date: '2025-01-30',
    readingTime: '7 min read',
    tags: ['GIS', 'Geoportal', 'Infrastructure'],
  },
  {
    slug: 'virtualisasi-proxmox-docker-pemerintah',
    title: 'Virtualisasi & Containerisasi di Lingkungan Pemerintah',
    excerpt: 'Efisiensi resource dan kemudahan maintenance dengan Proxmox VE dan Docker Engine.',
    date: '2025-01-20',
    readingTime: '8 min read',
    tags: ['Proxmox', 'Docker', 'DevOps'],
  },
];
