import { Project, Skill, BlogPost } from '@/types';

export const projects: Project[] = [
  {
    slug: 'e-commerce-platform',
    title: 'Modern E-Commerce Platform',
    description: 'A high-performance e-commerce solution built with Next.js, Stripe, and PostgreSQL.',
    featured: true,
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Prisma', 'Stripe'],
    image: '/projects/ecommerce.png',
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
  },
  {
    slug: 'ai-task-manager',
    title: 'AI-Powered Task Manager',
    description: 'An intelligent task management system with automated prioritization and scheduling.',
    featured: true,
    tags: ['React', 'Node.js', 'OpenAI', 'MongoDB'],
    image: '/projects/taskai.png',
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
  },
  {
    slug: 'real-time-collaboration',
    title: 'Real-time Collaboration Suite',
    description: 'Secure and fast real-time document editing and team chat application.',
    featured: true,
    tags: ['Socket.io', 'Express', 'Redis', 'React'],
    image: '/projects/collab.png',
    githubUrl: 'https://github.com',
  },
  {
    slug: 'cloud-infra-dashboard',
    title: 'Cloud Infrastructure Dashboard',
    description: 'A unified interface for managing multi-cloud resources and monitoring system health.',
    featured: true,
    tags: ['Next.js', 'Docker', 'AWS', 'Grafana'],
    image: '/projects/cloud.png',
    githubUrl: 'https://github.com',
  },
  {
    slug: 'blockchain-analytics',
    title: 'Blockchain Analytics Platform',
    description: 'Real-time tracking and visualization of on-chain transactions and token metrics.',
    featured: true,
    tags: ['Rust', 'PostgreSQL', 'Three.js', 'TypeScript'],
    image: '/projects/blockchain.png',
    githubUrl: 'https://github.com',
  },
  {
    slug: 'iot-smart-home',
    title: 'IoT Smart Home Hub',
    description: 'Centralized control system for smart home devices with local-first processing.',
    featured: true,
    tags: ['Go', 'MQTT', 'React Native', 'SQLite'],
    image: '/projects/iot.png',
    githubUrl: 'https://github.com',
  },
];

export const skills: Skill[] = [
  { name: 'TypeScript', category: 'Language', level: 90 },
  { name: 'JavaScript', category: 'Language', level: 95 },
  { name: 'Python', category: 'Language', level: 80 },
  { name: 'Go', category: 'Language', level: 70 },
  { name: 'React', category: 'Frontend', level: 95 },
  { name: 'Next.js', category: 'Frontend', level: 90 },
  { name: 'Tailwind CSS', category: 'Frontend', level: 95 },
  { name: 'Node.js', category: 'Backend', level: 85 },
  { name: 'PostgreSQL', category: 'Database', level: 80 },
  { name: 'Docker', category: 'DevOps', level: 75 },
];

export const blogs: BlogPost[] = [
  {
    slug: 'scaling-nextjs-apps',
    title: 'Scaling Next.js Applications for Production',
    excerpt: 'Learn about the best practices for performance and SEO in large-scale Next.js projects.',
    date: '2024-03-20',
    readingTime: '8 min read',
    tags: ['Next.js', 'Architecture', 'Performance'],
  },
  {
    slug: 'mastering-typescript-generics',
    title: 'Mastering TypeScript Generics',
    excerpt: 'Deep dive into complex generic patterns and how they can improve your type safety.',
    date: '2024-03-15',
    readingTime: '6 min read',
    tags: ['TypeScript', 'Development'],
  },
  {
    slug: 'microservices-vs-monoliths',
    title: 'Microservices vs Monoliths: The Honest Trade-offs',
    excerpt: 'When should you actually switch to microservices? Avoid the hype and understand the operational cost.',
    date: '2024-03-10',
    readingTime: '10 min read',
    tags: ['Backend', 'Architecture'],
  },
  {
    slug: 'the-rise-of-edge-computing',
    title: 'The Rise of Edge Computing in Modern Web',
    excerpt: 'Deploying logic closer to users. How Vercel and Cloudflare are changing the infrastructure game.',
    date: '2024-03-05',
    readingTime: '7 min read',
    tags: ['Infrastructure', 'Performance'],
  },
  {
    slug: 'rust-for-web-developers',
    title: 'Why Web Developers are Learning Rust in 2024',
    excerpt: 'From WASM to high-performance CLI tools, Rust is becoming a must-have skill for senior engineers.',
    date: '2024-02-28',
    readingTime: '12 min read',
    tags: ['Rust', 'Languages'],
  },
  {
    slug: 'effective-code-review-culture',
    title: 'Building an Effective Code Review Culture',
    excerpt: 'Code reviews are for team growth, not just catching bugs. Learn how to give and receive feedback.',
    date: '2024-02-20',
    readingTime: '5 min read',
    tags: ['Engineering', 'Soft Skills'],
  },
  {
    slug: 'modern-state-management',
    title: 'State Management in React: Beyond Redux',
    excerpt: 'Exploring Zustand, Jotai, and Signals. Choosing the right tool for your application complexity.',
    date: '2024-02-15',
    readingTime: '8 min read',
    tags: ['React', 'Frontend'],
  },
  {
    slug: 'understanding-db-indexing',
    title: 'Understanding Database Indexing for Faster Queries',
    excerpt: 'A deep dive into B-Trees, Hash indexes, and how to optimize your SQL queries for scale.',
    date: '2024-02-05',
    readingTime: '9 min read',
    tags: ['Database', 'Optimization'],
  },
];
